#pragma once
#include <UEFIDef.h>

namespace EFI
{
	struct EFI_UNICODE_CTRL_CHAR
	{
	public:
		static CONST CHAR16 NUL = 0x0000;
		static CONST CHAR16 BACKSPACE = 0x0008;
		static CONST CHAR16 TAB = 0x0009;
		static CONST CHAR16 LF = 0x000A;
		static CONST CHAR16 CR = 0x000D;
		static CONST CHAR16 ESC = 0x001B;
	};

	//******************************************************
	// UNICODE DRAWING CHARACTERS
	//******************************************************
	struct EFI_UNICODE_DRAWING_CHAR
	{
	public:

		static CONST CHAR16 BOXDRAW_HORIZONTAL = 0x2500;
		static CONST CHAR16 BOXDRAW_VERTICAL = 0x2502;
		static CONST CHAR16 BOXDRAW_DOWN_RIGHT = 0x250c;
		static CONST CHAR16 BOXDRAW_DOWN_LEFT = 0x2510;
		static CONST CHAR16 BOXDRAW_UP_RIGHT = 0x2514;
		static CONST CHAR16 BOXDRAW_UP_LEFT = 0x2518;
		static CONST CHAR16 BOXDRAW_VERTICAL_RIGHT = 0x251c;
		static CONST CHAR16 BOXDRAW_VERTICAL_LEFT = 0x2524;
		static CONST CHAR16 BOXDRAW_DOWN_HORIZONTAL = 0x252c;
		static CONST CHAR16 BOXDRAW_UP_HORIZONTAL = 0x2534;
		static CONST CHAR16 BOXDRAW_VERTICAL_HORIZONTAL = 0x253c;

		static CONST CHAR16 BOXDRAW_DOUBLE_HORIZONTAL = 0x2550;
		static CONST CHAR16 BOXDRAW_DOUBLE_VERTICAL = 0x2551;
		static CONST CHAR16 BOXDRAW_DOWN_RIGHT_DOUBLE = 0x2552;
		static CONST CHAR16 BOXDRAW_DOWN_DOUBLE_RIGHT = 0x2553;
		static CONST CHAR16 BOXDRAW_DOUBLE_DOWN_RIGHT = 0x2554;
		static CONST CHAR16 BOXDRAW_DOWN_LEFT_DOUBLE = 0x2555;
		static CONST CHAR16 BOXDRAW_DOWN_DOUBLE_LEFT = 0x2556;
		static CONST CHAR16 BOXDRAW_DOUBLE_DOWN_LEFT = 0x2557;
		
		static CONST CHAR16 BOXDRAW_UP_RIGHT_DOUBLE = 0x2558;
		static CONST CHAR16 BOXDRAW_UP_DOUBLE_RIGHT = 0x2559;
		static CONST CHAR16 BOXDRAW_DOUBLE_UP_RIGHT = 0x255a;
		static CONST CHAR16 BOXDRAW_UP_LEFT_DOUBLE = 0x255b;
		static CONST CHAR16 BOXDRAW_UP_DOUBLE_LEFT = 0x255c;
		static CONST CHAR16 BOXDRAW_DOUBLE_UP_LEFT = 0x255d;
		
		static CONST CHAR16 BOXDRAW_VERTICAL_RIGHT_DOUBLE = 0x255e;
		static CONST CHAR16 BOXDRAW_VERTICAL_DOUBLE_RIGHT = 0x255f;
		static CONST CHAR16 BOXDRAW_DOUBLE_VERTICAL_RIGHT = 0x2560;
		
		static CONST CHAR16 BOXDRAW_VERTICAL_LEFT_DOUBLE = 0x2561;
		static CONST CHAR16 BOXDRAW_VERTICAL_DOUBLE_LEFT = 0x2562;
		static CONST CHAR16 BOXDRAW_DOUBLE_VERTICAL_LEFT = 0x2563;
		
		static CONST CHAR16 BOXDRAW_DOWN_HORIZONTAL_DOUBLE = 0x2564;
		static CONST CHAR16 BOXDRAW_DOWN_DOUBLE_HORIZONTAL = 0x2565;
		static CONST CHAR16 BOXDRAW_DOUBLE_DOWN_HORIZONTAL = 0x2566;
		
		static CONST CHAR16 BOXDRAW_UP_HORIZONTAL_DOUBLE = 0x2567;
		static CONST CHAR16 BOXDRAW_UP_DOUBLE_HORIZONTAL = 0x2568;
		static CONST CHAR16 BOXDRAW_DOUBLE_UP_HORIZONTAL = 0x2569;
		
		static CONST CHAR16 BOXDRAW_VERTICAL_HORIZONTAL_DOUBLE = 0x256a;
		static CONST CHAR16 BOXDRAW_VERTICAL_DOUBLE_HORIZONTAL = 0x256b;
		static CONST CHAR16 BOXDRAW_DOUBLE_VERTICAL_HORIZONTAL = 0x256c;
		
		//******************************************************
		// EFI Required Block Elements Code Chart
		//******************************************************
		
		static CONST CHAR16 BLOCKELEMENT_FULL_BLOCK = 0x2588;
		static CONST CHAR16 BLOCKELEMENT_LIGHT_SHADE = 0x2591;
		
		//******************************************************
		// EFI Required Geometric Shapes Code Chart
		//******************************************************
		
		static CONST CHAR16 GEOMETRICSHAPE_UP_TRIANGLE = 0x25b2;
		static CONST CHAR16 GEOMETRICSHAPE_RIGHT_TRIANGLE = 0x25ba;
		static CONST CHAR16 GEOMETRICSHAPE_DOWN_TRIANGLE = 0x25bc;
		static CONST CHAR16 GEOMETRICSHAPE_LEFT_TRIANGLE = 0x25c4;
		
		//******************************************************
		// EFI Required Arrow shapes
		//******************************************************
		
		static CONST CHAR16 ARROW_UP = 0x2191;
		static CONST CHAR16 ARROW_DOWN = 0x2193;
	};
}
