<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
	<PublishAot>true</PublishAot>
	<TrimMode>link</TrimMode>
	<PublishSingleFile>true</PublishSingleFile>
	<!-- Keep implicit framework references disabled; compile against UEFIRefs minimal reference assemblies -->
	<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
  </PropertyGroup>
	<ItemGroup>

	</ItemGroup>


  <ItemGroup>
	<!-- Reference the small reference-assembly project that provides minimal attributes/types -->
	<ProjectReference Include="..\UEFIRefs\UEFIRefs.csproj" />
  </ItemGroup>
</Project>
