#pragma once

#include "UEFIDef.h"
#include "EFI_STATUS.h"
#include "EFI_GUID.h"
#include "EFI_STOP_BITS_TYPE.h"
#include "EFI_PARITY_TYPE.h"
#include "EFI_SERIAL_CONTORL_BITS.h"
#include "EFI_SERIAL_IO_MODE.h"

namespace EFI
{
	struct EFI_SERIAL_IO_PROTOCOL;

	constinit  const ALIGN(8) EFI::EFI_GUID EFI_SERIAL_IO_PROTOCOL_GUID =          { 0xBB25CF6F, 0xF1D4, 0x11D2, {0x9a, 0x0c, 0x00, 0x90, 0x27, 0x3f, 0xc1, 0xfd}};
	constinit  const ALIGN(8) EFI::EFI_GUID EFI_SERIAL_TERMINAL_DEVICE_TYPE_GUID = { 0x6ad9a60f, 0x5815, 0x4c7c, {0x8a, 0x10, 0x50, 0x53, 0xd2, 0xbf, 0x7a, 0x1b} };

	const UINT32 EFI_SERIAL_IO_PROTOCOL_REVISION = 0x00010000;
	const UINT32 EFI_SERIAL_IO_PROTOCOL_REVISION1p1 = 0x00010001;

     typedef EFI_STATUS (EFIAPI* EFI_SERIAL_RESET)(EFI_SERIAL_IO_PROTOCOL* This);

     typedef EFI_STATUS (EFIAPI* EFI_SERIAL_SET_ATTRIBUTES)(EFI_SERIAL_IO_PROTOCOL* This,
         UINT64 BaudRate, UINT32 ReceiveFifoDepth, UINT32 Timeout,
         EFI_PARITY_TYPE Parity, UINT8 DataBits, EFI_STOP_BITS_TYPE StopBits);

     typedef EFI_STATUS (EFIAPI* EFI_SERIAL_SET_CONTROL_BITS)(EFI_SERIAL_IO_PROTOCOL* This,
         EFI_SERIAL_CONTROL_BITS Control);

     typedef EFI_STATUS (EFIAPI* EFI_SERIAL_GET_CONTROL_BITS)(EFI_SERIAL_IO_PROTOCOL* This,
         EFI_SERIAL_CONTROL_BITS* Control);

     typedef EFI_STATUS (EFIAPI* EFI_SERIAL_WRITE)(EFI_SERIAL_IO_PROTOCOL* This,
         UINTN* BufferSize, VOID* Buffer);

     typedef EFI_STATUS (EFIAPI* EFI_SERIAL_READ)(EFI_SERIAL_IO_PROTOCOL* This,
         UINTN* BufferSize, VOID* Buffer);

	 struct EFI_SERIAL_IO_PROTOCOL
	 {
	 public:
		 UINT32 Revision;
		 EFI_SERIAL_RESET Reset;
		 EFI_SERIAL_SET_ATTRIBUTES SetAttributes;
		 EFI_SERIAL_SET_CONTROL_BITS SetControl;
		 EFI_SERIAL_GET_CONTROL_BITS GetControl;
		 EFI_SERIAL_WRITE Write;
		 EFI_SERIAL_READ Read;
		 EFI_SERIAL_IO_MODE* Mode;
		 CONST EFI_GUID* DeviceTypeGuid; // Revision 1.1
	 };
}
