#pragma once
#include "UEFIDef.h"

namespace EFI
{
	enum class EFI_SERIAL_CONTROL_BITS : UINT16
	{
		EFI_SERIAL_CLEAR_TO_SEND = 0x0010,
		EFI_SERIAL_DATA_SET_READY = 0x0020,
		EFI_SERIAL_RING_INDICATE = 0x0040,
		EFI_SERIAL_CARRIER_DETECT = 0x0080,
		EFI_SERIAL_REQUEST_TO_SEND = 0x0002,
		EFI_SERIAL_DATA_TERMINAL_READY = 0x0001,
		EFI_SERIAL_INPUT_BUFFER_EMPTY = 0x0100,
		EFI_SERIAL_OUTPUT_BUFFER_EMPTY = 0x0200,
		EFI_SERIAL_HARDWARE_LOOPBACK_ENABLE = 0x1000,
		EFI_SERIAL_SOFTWARE_LOOPBACK_ENABLE = 0x2000,
		EFI_SERIAL_HARDWARE_FLOW_CONTROL_ENABLE = 0x4000,
	};

}
