#pragma once

#include "UEFIDef.h"
#include "EFI_STATUS.h"
#include "EFI_GUID.h"
#include "EFI_GRAPHICS_OUTPUT_MODE_INFORMATION.h"
#include "EFI_GRAPHICS_OUTPUT_BLT_PIXEL.h"
#include "EFI_GRAPHICS_OUTPUT_BLT_OPERATION.h"
#include "EFI_GRAPHICS_OUTPUT_PROTOCOL_MODE.h"

namespace EFI
{
	struct EFI_GRAPHICS_OUTPUT_PROTOCOL;

	constinit const struct EFI::EFI_GUID EFI_GRAPHICS_OUTPUT_PROTOCOL_GUID = { 0x9042a9de, 0x23dc,0x4a38, { 0x96, 0xfb, 0x7a, 0xde, 0xd0, 0x80, 0x51, 0x6a }};

	typedef EFI::EFI_STATUS (EFIAPI* EFI_GRAPHICS_OUTPUT_PROTOCOL_QUERY_MODE) (IN EFI_GRAPHICS_OUTPUT_PROTOCOL* This,IN UINT32 Modenumber,OUT UINTN* SizeOfInfo, OUT EFI_GRAPHICS_OUTPUT_MODE_INFORMATION** Info);
	typedef EFI::EFI_STATUS (EFIAPI* EFI_GRAPHICS_OUTPUT_PROTOCOL_SET_MODE) (IN EFI_GRAPHICS_OUTPUT_PROTOCOL* This, IN UINT32 Modenumber);

	typedef EFI::EFI_STATUS (EFIAPI* EFI_GRAPHICS_OUTPUT_PROTOCOL_BLT) ( IN EFI_GRAPHICS_OUTPUT_PROTOCOL* This, IN OUT EFI_GRAPHICS_OUTPUT_BLT_PIXEL* BltBuffer,
		OPTIONAL IN EFI_GRAPHICS_OUTPUT_BLT_OPERATION BltOperation,IN UINTN SourceX,IN UINTN SourceY,IN UINTN DestinationX,IN UINTN DestinationY,IN UINTN Width,IN UINTN Height,
		IN UINTN Delta OPTIONAL);

	struct EFI_GRAPHICS_OUTPUT_PROTOCOL
	{
	public:
		EFI::EFI_GRAPHICS_OUTPUT_PROTOCOL_QUERY_MODE QueryMode;
		EFI::EFI_GRAPHICS_OUTPUT_PROTOCOL_SET_MODE SetMode;
		EFI::EFI_GRAPHICS_OUTPUT_PROTOCOL_BLT Blt;
		EFI::EFI_GRAPHICS_OUTPUT_PROTOCOL_MODE* Mode;
	};
}