#pragma once
#include "UEFIDef.h"

namespace EFI
{
	typedef UINTN EFI_TPL;
	

	CONST UINTN EFI_TPL_APPLICATION = 4;
	CONST UINTN EFI_TPL_CALLBACK = 8;
	CONST UINTN EFI_TPL_NOTIFY = 16;
	CONST UINTN EFI_TPL_HIGH_LEVEL = 31;
};
